// GENERATED by build/build.js — do not edit by hand.
const SEARCH_INDEX = [
  {
    "title": "Setting Up Your Email Sending Subdomain",
    "description": "Enable email sending from Storyraise by configuring a custom subdomain with SPF, DKIM, and tracking DNS records.",
    "url": "/docs/email-subdomain-setup/",
    "keywords": [
      "email",
      "dns",
      "subdomain",
      "spf",
      "dkim",
      "setup",
      "sending",
      "domain",
      "records",
      "cloudflare",
      "godaddy"
    ]
  },
  {
    "title": "What is Storyraise?",
    "description": "Storyraise helps nonprofits turn their impact into beautiful, interactive web reports — annual reports, impact reports, donor updates, event recaps, and more…",
    "url": "/docs/getting-started/what-is-storyraise/",
    "keywords": [
      "what",
      "storyraise",
      "getting",
      "started"
    ]
  },
  {
    "title": "Creating your first report",
    "description": "You can have a working draft of your first report in just a few minutes. This guide walks you from an empty dashboard to a report you're ready to fill in.",
    "url": "/docs/getting-started/creating-your-first-report/",
    "keywords": [
      "creating",
      "first",
      "report",
      "getting",
      "started"
    ]
  },
  {
    "title": "Understanding templates",
    "description": "Templates give you a complete, professionally designed report structure to start from — sections, layouts, and sample content are already in place, so you can…",
    "url": "/docs/getting-started/understanding-templates/",
    "keywords": [
      "understanding",
      "templates",
      "getting",
      "started"
    ]
  },
  {
    "title": "Publishing and sharing reports",
    "description": "Until you publish, your report is a private draft only your team can see. Publishing puts it on the web at its own link, ready to share with donors,…",
    "url": "/docs/getting-started/publishing-and-sharing/",
    "keywords": [
      "publishing",
      "sharing",
      "reports",
      "getting",
      "started"
    ]
  },
  {
    "title": "PDF exports",
    "description": "Web reports are great for sharing online, but sometimes you need a file — something to print, mail, attach to an email, or hand to your board. The PDF Builder…",
    "url": "/docs/getting-started/pdf-exports/",
    "keywords": [
      "pdf",
      "exports",
      "getting",
      "started"
    ]
  },
  {
    "title": "User roles and permissions",
    "description": "Storyraise is organized around your organization: a shared workspace that holds your reports, folders, constituent data, brand kit, and team. Everyone you…",
    "url": "/docs/getting-started/user-roles-and-permissions/",
    "keywords": [
      "user",
      "roles",
      "permissions",
      "getting",
      "started"
    ]
  },
  {
    "title": "Common terminology",
    "description": "A quick reference for the words you'll see throughout Storyraise.",
    "url": "/docs/getting-started/common-terminology/",
    "keywords": [
      "common",
      "terminology",
      "getting",
      "started"
    ]
  },
  {
    "title": "Connecting a CRM",
    "description": "Connecting your CRM brings your constituents — donors, members, volunteers — into Storyraise. Once they're in, you can personalize reports for each…",
    "url": "/docs/crm-and-data/connecting-a-crm/",
    "keywords": [
      "connecting",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Importing constituent data",
    "description": "You can bring constituents into Storyraise two ways: sync them from a connected CRM, or upload a CSV file. CSV import works with data exported from any system…",
    "url": "/docs/crm-and-data/importing-constituent-data/",
    "keywords": [
      "importing",
      "constituent",
      "data",
      "crm",
      "connections"
    ]
  },
  {
    "title": "Mapping fields",
    "description": "Coming soon — a visual field-mapping step is on our roadmap. Today, Storyraise imports your fields automatically using the rules described below.",
    "url": "/docs/crm-and-data/mapping-fields/",
    "keywords": [
      "mapping",
      "fields",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Data refreshes",
    "description": "Your CRM data changes constantly — new donors, updated emails, fresh gift records. This page covers how to keep your Storyraise constituent list in step.",
    "url": "/docs/crm-and-data/data-refreshes/",
    "keywords": [
      "data",
      "refreshes",
      "crm",
      "connections"
    ]
  },
  {
    "title": "Troubleshooting sync issues",
    "description": "Most sync problems come down to one of a few causes. Work through the section that matches what you're seeing.",
    "url": "/docs/crm-and-data/troubleshooting-sync-issues/",
    "keywords": [
      "troubleshooting",
      "sync",
      "issues",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Supported integrations",
    "description": "Here's where Storyraise's data connections stand today, and what's on the way.",
    "url": "/docs/crm-and-data/supported-integrations/",
    "keywords": [
      "supported",
      "integrations",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Blackbaud (Raiser's Edge NXT)",
    "description": "Connect Storyraise to Blackbaud to sync constituents from Raiser's Edge NXT, so you can personalize reports for your donors and see who's engaging.",
    "url": "/docs/crm-and-data/integrations/blackbaud-raisers-edge-nxt/",
    "keywords": [
      "blackbaud",
      "raiser",
      "edge",
      "nxt",
      "crm",
      "data",
      "connections",
      "raisers"
    ]
  },
  {
    "title": "Bloomerang",
    "description": "Connect Storyraise to Bloomerang to sync your constituents, so you can personalize reports for your donors and see who's engaging.",
    "url": "/docs/crm-and-data/integrations/bloomerang/",
    "keywords": [
      "bloomerang",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Givebutter",
    "description": "Embed your Givebutter giving experience directly inside a Storyraise report, so the moment your story moves a reader, they can give — without leaving the page.",
    "url": "/docs/crm-and-data/integrations/givebutter/",
    "keywords": [
      "givebutter",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Virtuous",
    "description": "Coming soon — a native Virtuous integration is on our roadmap and isn't available yet.",
    "url": "/docs/crm-and-data/integrations/virtuous/",
    "keywords": [
      "virtuous",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "HubSpot",
    "description": "Coming soon — a native HubSpot integration is on our roadmap and isn't available yet.",
    "url": "/docs/crm-and-data/integrations/hubspot/",
    "keywords": [
      "hubspot",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "CiviCRM",
    "description": "Coming soon — a native CiviCRM integration is on our roadmap and isn't available yet.",
    "url": "/docs/crm-and-data/integrations/civicrm/",
    "keywords": [
      "civicrm",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Adding sections",
    "description": "Reports are built section by section. Each section is a full-width page of your report with its own layout and purpose — an intro, a story, a stats spread, a…",
    "url": "/docs/building-reports/adding-sections/",
    "keywords": [
      "adding",
      "sections",
      "building",
      "reports"
    ]
  },
  {
    "title": "Editing content",
    "description": "Everything in a Storyraise report is edited directly on the canvas — what you see while editing is what readers see. This page covers how sections, blocks,…",
    "url": "/docs/building-reports/editing-content/",
    "keywords": [
      "editing",
      "content",
      "building",
      "reports"
    ]
  },
  {
    "title": "Using templates",
    "description": "Templates do the design work so you can focus on the story. This page covers working with templates while you build. (New to templates? Start with…",
    "url": "/docs/building-reports/using-templates/",
    "keywords": [
      "using",
      "templates",
      "building",
      "reports"
    ]
  },
  {
    "title": "Brand kit",
    "description": "Your brand kit stores your organization's logos, images, colors, and fonts in one place, available in every report. Set it up once and every report you build…",
    "url": "/docs/building-reports/brand-kit/",
    "keywords": [
      "brand",
      "kit",
      "building",
      "reports"
    ]
  },
  {
    "title": "Fonts and colors",
    "description": "Typography and color do most of the visual work in a report. This page covers how to choose and apply both.",
    "url": "/docs/building-reports/fonts-and-colors/",
    "keywords": [
      "fonts",
      "colors",
      "building",
      "reports"
    ]
  },
  {
    "title": "Images and videos",
    "description": "Photos and video carry the emotional weight of a report. This page covers getting media in, making it look great, and keeping it fast.",
    "url": "/docs/building-reports/images-and-videos/",
    "keywords": [
      "images",
      "videos",
      "building",
      "reports"
    ]
  },
  {
    "title": "AI content generation",
    "description": "Storyraise has AI built in to help with the hardest part of any report: the blank page. Use it to draft whole sections and to generate imagery — then make the…",
    "url": "/docs/building-reports/ai-content-generation/",
    "keywords": [
      "content",
      "generation",
      "building",
      "reports"
    ]
  },
  {
    "title": "Reordering sections",
    "description": "The order of your sections is the arc of your story. Storyraise makes it easy to rearrange sections as your report takes shape.",
    "url": "/docs/building-reports/reordering-sections/",
    "keywords": [
      "reordering",
      "sections",
      "building",
      "reports"
    ]
  },
  {
    "title": "Navigation options",
    "description": "Published reports come with built-in navigation so readers can jump straight to what interests them — or simply scroll from top to bottom. This page covers…",
    "url": "/docs/building-reports/navigation-options/",
    "keywords": [
      "navigation",
      "options",
      "building",
      "reports"
    ]
  },
  {
    "title": "Mobile optimization",
    "description": "Many of your readers will open your report on a phone — often from an email or social link. Storyraise reports are responsive out of the box, and the builder…",
    "url": "/docs/building-reports/mobile-optimization/",
    "keywords": [
      "mobile",
      "optimization",
      "building",
      "reports"
    ]
  },
  {
    "title": "Accessibility considerations",
    "description": "An accessible report reaches your whole audience — including readers with low vision, color blindness, motor differences, or those using screen readers. Most…",
    "url": "/docs/building-reports/accessibility/",
    "keywords": [
      "accessibility",
      "considerations",
      "building",
      "reports"
    ]
  },
  {
    "title": "Sharing reports",
    "description": "Publishing puts your report on the web — sharing puts it in front of your audience. Storyraise gives you several ways to distribute a published report, all…",
    "url": "/docs/distribution-and-engagement/sharing-reports/",
    "keywords": [
      "sharing",
      "reports",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "Personalized links",
    "description": "A personalized link opens your report addressed to one specific constituent — their name in the greeting, their details filled into merge tags, and their…",
    "url": "/docs/distribution-and-engagement/personalized-links/",
    "keywords": [
      "personalized",
      "links",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "Email distribution",
    "description": "Storyraise Send lets you deliver your reports and messages to constituents by email, right from Storyraise — personalized for each recipient, with no separate…",
    "url": "/docs/distribution-and-engagement/email-distribution/",
    "keywords": [
      "email",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "SMS distribution",
    "description": "Text messages get seen — most are read within minutes. Storyraise Send lets you deliver your reports and messages to constituents by SMS, each text…",
    "url": "/docs/distribution-and-engagement/sms-distribution/",
    "keywords": [
      "sms",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "Tracking engagement",
    "description": "Every published Storyraise report quietly keeps score: who opened it, what they read, and what they did next. There's nothing to configure — tracking is built…",
    "url": "/docs/distribution-and-engagement/tracking-engagement/",
    "keywords": [
      "tracking",
      "engagement",
      "distribution"
    ]
  },
  {
    "title": "Understanding report metrics",
    "description": "Once your report is published and shared, Insights shows you how it's performing. From the dashboard, open a published report's menu and choose View Insights.…",
    "url": "/docs/distribution-and-engagement/understanding-report-metrics/",
    "keywords": [
      "understanding",
      "report",
      "metrics",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "Video analytics",
    "description": "Coming soon — viewing analytics for Storyraise Video are in development and not yet available.",
    "url": "/docs/distribution-and-engagement/video-analytics/",
    "keywords": [
      "video",
      "analytics",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "What is Storyraise Video?",
    "description": "Storyraise Video turns one recording into hundreds of personal video messages. Record once, and every constituent receives a version addressed to them — their…",
    "url": "/docs/products/storyraise-video/",
    "keywords": [
      "what",
      "storyraise",
      "video",
      "products"
    ]
  },
  {
    "title": "What is Storyraise Collect?",
    "description": "Storyraise Collect gathers the raw material your stories are made of. Build a form, share the link, and collect stories, thank-yous, photos, and data from…",
    "url": "/docs/products/storyraise-collect/",
    "keywords": [
      "what",
      "storyraise",
      "collect",
      "products"
    ]
  },
  {
    "title": "Best practices",
    "description": "Patterns that separate the reports people finish from the ones they skim. Distilled from what works across Storyraise customers — use them as defaults, break…",
    "url": "/docs/resources/best-practices/",
    "keywords": [
      "best",
      "practices",
      "resources"
    ]
  },
  {
    "title": "Frequently asked questions",
    "description": "Quick answers to the questions we hear most. Each links to a fuller guide.",
    "url": "/docs/resources/faq/",
    "keywords": [
      "frequently",
      "asked",
      "questions",
      "resources",
      "faq"
    ]
  }
];
