// GENERATED by build/build.js — do not edit by hand.
const SEARCH_INDEX = [
  {
    "title": "What is Storyraise?",
    "description": "Storyraise helps nonprofits turn their impact into beautiful, interactive web reports — annual reports, impact reports, donor updates, event recaps, and more…",
    "url": "/docs/getting-started/what-is-storyraise/",
    "keywords": [
      "what",
      "storyraise",
      "getting",
      "started"
    ]
  },
  {
    "title": "Creating your first report",
    "description": "You can have a working draft of your first report in just a few minutes. This guide walks you from an empty dashboard to a report you're ready to fill in.",
    "url": "/docs/getting-started/creating-your-first-report/",
    "keywords": [
      "creating",
      "first",
      "report",
      "getting",
      "started"
    ]
  },
  {
    "title": "Understanding templates",
    "description": "Templates give you a complete, professionally designed report structure to start from — sections, layouts, and sample content are already in place, so you can…",
    "url": "/docs/getting-started/understanding-templates/",
    "keywords": [
      "understanding",
      "templates",
      "getting",
      "started"
    ]
  },
  {
    "title": "Publishing and sharing reports",
    "description": "Until you publish, your report is a private draft only your team can see. Publishing puts it on the web at its own link, ready to share with donors,…",
    "url": "/docs/getting-started/publishing-and-sharing/",
    "keywords": [
      "publishing",
      "sharing",
      "reports",
      "getting",
      "started"
    ]
  },
  {
    "title": "PDF exports",
    "description": "Web reports are great for sharing online, but sometimes you need a file — something to print, mail, attach to an email, or hand to your board. The PDF Builder…",
    "url": "/docs/getting-started/pdf-exports/",
    "keywords": [
      "pdf",
      "exports",
      "getting",
      "started",
      "print",
      "download",
      "page size",
      "bleed"
    ]
  },
  {
    "title": "User roles and permissions",
    "description": "Storyraise is organized around your organization: a shared workspace that holds your reports, folders, constituent data, brand kit, and team. Everyone you…",
    "url": "/docs/getting-started/user-roles-and-permissions/",
    "keywords": [
      "user",
      "roles",
      "permissions",
      "getting",
      "started"
    ]
  },
  {
    "title": "Common terminology",
    "description": "A quick reference for the words you'll see throughout Storyraise.",
    "url": "/docs/getting-started/common-terminology/",
    "keywords": [
      "common",
      "terminology",
      "getting",
      "started"
    ]
  },
  {
    "title": "Connecting a CRM",
    "description": "Connecting your CRM brings your constituents — donors, members, volunteers — into Storyraise. Once they're in, you can personalize reports for each…",
    "url": "/docs/crm-and-data/connecting-a-crm/",
    "keywords": [
      "connecting",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Importing constituent data",
    "description": "You can bring constituents into Storyraise two ways: sync them from a connected CRM, or upload a CSV file. CSV import works with data exported from any system…",
    "url": "/docs/crm-and-data/importing-constituent-data/",
    "keywords": [
      "importing",
      "constituent",
      "data",
      "crm",
      "connections",
      "csv",
      "upload",
      "donors",
      "import"
    ]
  },
  {
    "title": "Mapping fields",
    "description": "Coming soon — a visual field-mapping step is on our roadmap. Today, Storyraise imports your fields automatically using the rules described below.",
    "url": "/docs/crm-and-data/mapping-fields/",
    "keywords": [
      "mapping",
      "fields",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Data refreshes",
    "description": "Your CRM data changes constantly — new donors, updated emails, fresh gift records. This page covers how to keep your Storyraise constituent list in step.",
    "url": "/docs/crm-and-data/data-refreshes/",
    "keywords": [
      "data",
      "refreshes",
      "crm",
      "connections"
    ]
  },
  {
    "title": "Troubleshooting sync issues",
    "description": "Most sync problems come down to one of a few causes. Work through the section that matches what you're seeing.",
    "url": "/docs/crm-and-data/troubleshooting-sync-issues/",
    "keywords": [
      "troubleshooting",
      "sync",
      "issues",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Supported integrations",
    "description": "Here's where Storyraise's data connections stand today, and what's on the way.",
    "url": "/docs/crm-and-data/supported-integrations/",
    "keywords": [
      "supported",
      "integrations",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Blackbaud (Raiser's Edge NXT)",
    "description": "Connect Storyraise to Blackbaud to sync constituents from Raiser's Edge NXT, so you can personalize reports for your donors and see who's engaging.",
    "url": "/docs/crm-and-data/integrations/blackbaud-raisers-edge-nxt/",
    "keywords": [
      "blackbaud",
      "raiser",
      "edge",
      "nxt",
      "crm",
      "data",
      "connections",
      "raisers"
    ]
  },
  {
    "title": "Bloomerang",
    "description": "Connect Storyraise to Bloomerang to sync your constituents, so you can personalize reports for your donors and see who's engaging.",
    "url": "/docs/crm-and-data/integrations/bloomerang/",
    "keywords": [
      "bloomerang",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Givebutter",
    "description": "Embed your Givebutter giving experience directly inside a Storyraise report, so the moment your story moves a reader, they can give — without leaving the page.",
    "url": "/docs/crm-and-data/integrations/givebutter/",
    "keywords": [
      "givebutter",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Virtuous",
    "description": "Coming soon — a native Virtuous integration is on our roadmap and isn't available yet.",
    "url": "/docs/crm-and-data/integrations/virtuous/",
    "keywords": [
      "virtuous",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "HubSpot",
    "description": "Coming soon — a native HubSpot integration is on our roadmap and isn't available yet.",
    "url": "/docs/crm-and-data/integrations/hubspot/",
    "keywords": [
      "hubspot",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "CiviCRM",
    "description": "Coming soon — a native CiviCRM integration is on our roadmap and isn't available yet.",
    "url": "/docs/crm-and-data/integrations/civicrm/",
    "keywords": [
      "civicrm",
      "crm",
      "data",
      "connections"
    ]
  },
  {
    "title": "Adding sections",
    "description": "Reports are built section by section. Each section is a full-width page of your report with its own layout and purpose — an intro, a story, a stats spread, a…",
    "url": "/docs/building-reports/adding-sections/",
    "keywords": [
      "adding",
      "sections",
      "building",
      "reports"
    ]
  },
  {
    "title": "Editing content",
    "description": "Everything in a Storyraise report is edited directly on the canvas — what you see while editing is what readers see. This page covers how sections, blocks,…",
    "url": "/docs/building-reports/editing-content/",
    "keywords": [
      "editing",
      "content",
      "building",
      "reports"
    ]
  },
  {
    "title": "Using templates",
    "description": "Templates do the design work so you can focus on the story. This page covers working with templates while you build. (New to templates? Start with…",
    "url": "/docs/building-reports/using-templates/",
    "keywords": [
      "using",
      "templates",
      "building",
      "reports"
    ]
  },
  {
    "title": "Brand kit",
    "description": "Your brand kit stores your organization's logos, images, colors, and fonts in one place, available in every report. Set it up once and every report you build…",
    "url": "/docs/building-reports/brand-kit/",
    "keywords": [
      "brand",
      "kit",
      "building",
      "reports"
    ]
  },
  {
    "title": "Fonts and colors",
    "description": "Typography and color do most of the visual work in a report. This page covers how to choose and apply both.",
    "url": "/docs/building-reports/fonts-and-colors/",
    "keywords": [
      "fonts",
      "colors",
      "building",
      "reports"
    ]
  },
  {
    "title": "Images and videos",
    "description": "Photos and video carry the emotional weight of a report. This page covers getting media in, making it look great, and keeping it fast.",
    "url": "/docs/building-reports/images-and-videos/",
    "keywords": [
      "images",
      "videos",
      "building",
      "reports"
    ]
  },
  {
    "title": "Image sizes and dimensions",
    "description": "The right-shaped image makes a section look designed; the wrong-shaped one fights its layout. This guide lists the aspect ratio each section type expects, so…",
    "url": "/docs/building-reports/image-sizes-and-dimensions/",
    "keywords": [
      "image",
      "sizes",
      "dimensions",
      "building",
      "reports",
      "image size",
      "aspect ratio",
      "resolution",
      "crop",
      "pixels",
      "photo size"
    ]
  },
  {
    "title": "AI content generation",
    "description": "Storyraise has AI built in to help with the hardest part of any report: the blank page. Use it to draft whole sections and to generate imagery — then make the…",
    "url": "/docs/building-reports/ai-content-generation/",
    "keywords": [
      "ai",
      "content",
      "generation",
      "building",
      "reports",
      "gpt",
      "generate",
      "draft",
      "write"
    ]
  },
  {
    "title": "Reordering sections",
    "description": "The order of your sections is the arc of your story. Storyraise makes it easy to rearrange sections as your report takes shape.",
    "url": "/docs/building-reports/reordering-sections/",
    "keywords": [
      "reordering",
      "sections",
      "building",
      "reports"
    ]
  },
  {
    "title": "Navigation options",
    "description": "Published reports come with built-in navigation so readers can jump straight to what interests them — or simply scroll from top to bottom. This page covers…",
    "url": "/docs/building-reports/navigation-options/",
    "keywords": [
      "navigation",
      "options",
      "building",
      "reports"
    ]
  },
  {
    "title": "Mobile optimization",
    "description": "Many of your readers will open your report on a phone — often from an email or social link. Storyraise reports are responsive out of the box, and the builder…",
    "url": "/docs/building-reports/mobile-optimization/",
    "keywords": [
      "mobile",
      "optimization",
      "building",
      "reports"
    ]
  },
  {
    "title": "Accessibility considerations",
    "description": "An accessible report reaches your whole audience — including readers with low vision, color blindness, motor differences, or those using screen readers. Most…",
    "url": "/docs/building-reports/accessibility/",
    "keywords": [
      "accessibility",
      "considerations",
      "building",
      "reports"
    ]
  },
  {
    "title": "Sharing reports",
    "description": "Publishing puts your report on the web — sharing puts it in front of your audience. Storyraise gives you several ways to distribute a published report, all…",
    "url": "/docs/distribution-and-engagement/sharing-reports/",
    "keywords": [
      "sharing",
      "reports",
      "distribution",
      "engagement",
      "embed",
      "iframe",
      "qr",
      "copy link",
      "social"
    ]
  },
  {
    "title": "Personalized links",
    "description": "A personalized link opens your report addressed to one specific constituent — their name in the greeting, their details filled into merge tags, and their…",
    "url": "/docs/distribution-and-engagement/personalized-links/",
    "keywords": [
      "personalized",
      "links",
      "distribution",
      "engagement",
      "qr",
      "qr code",
      "merge tags",
      "for parameter",
      "unique url"
    ]
  },
  {
    "title": "Email distribution",
    "description": "Storyraise Send lets you deliver your reports and messages to constituents by email, right from Storyraise — personalized for each recipient, with no separate…",
    "url": "/docs/distribution-and-engagement/email-distribution/",
    "keywords": [
      "email",
      "distribution",
      "engagement",
      "send",
      "campaign",
      "newsletter",
      "blast"
    ]
  },
  {
    "title": "SMS distribution",
    "description": "Text messages get seen — most are read within minutes. Storyraise Send lets you deliver your reports and messages to constituents by SMS, each text…",
    "url": "/docs/distribution-and-engagement/sms-distribution/",
    "keywords": [
      "sms",
      "distribution",
      "engagement",
      "text message",
      "texting",
      "phone"
    ]
  },
  {
    "title": "Tracking engagement",
    "description": "Every published Storyraise report quietly keeps score: who opened it, what they read, and what they did next. There's nothing to configure — tracking is built…",
    "url": "/docs/distribution-and-engagement/tracking-engagement/",
    "keywords": [
      "tracking",
      "engagement",
      "distribution"
    ]
  },
  {
    "title": "Understanding report metrics",
    "description": "Once your report is published and shared, Insights shows you how it's performing. From the dashboard, open a published report's menu and choose View Insights.…",
    "url": "/docs/distribution-and-engagement/understanding-report-metrics/",
    "keywords": [
      "understanding",
      "report",
      "metrics",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "Video analytics",
    "description": "Coming soon — viewing analytics for Storyraise Video are in development and not yet available.",
    "url": "/docs/distribution-and-engagement/video-analytics/",
    "keywords": [
      "video",
      "analytics",
      "distribution",
      "engagement"
    ]
  },
  {
    "title": "Setting up your account",
    "description": "Getting started on Storyraise takes a couple of minutes. This guide walks you from the sign-up screen to your new dashboard.",
    "url": "/docs/account-and-settings/setting-up-your-account/",
    "keywords": [
      "setting",
      "account",
      "settings"
    ]
  },
  {
    "title": "Organization settings",
    "description": "Your organization is the shared workspace that holds your reports, constituents, brand kit, and team. This page covers the organization-level settings in your…",
    "url": "/docs/account-and-settings/organization-settings/",
    "keywords": [
      "organization",
      "settings",
      "account"
    ]
  },
  {
    "title": "Managing your team",
    "description": "Storyraise is built for teams. Invite colleagues into your organization so you can build reports together, divide up the work, and review each other's drafts.",
    "url": "/docs/account-and-settings/managing-your-team/",
    "keywords": [
      "managing",
      "team",
      "account",
      "settings",
      "invite",
      "collaborators",
      "members",
      "remove user"
    ]
  },
  {
    "title": "Your profile and security",
    "description": "This page covers your personal account — your name and sign-in details — and how to secure it with two-step verification.",
    "url": "/docs/account-and-settings/profile-and-security/",
    "keywords": [
      "profile",
      "security",
      "account",
      "settings",
      "mfa",
      "2fa",
      "two-step verification",
      "authenticator",
      "password reset",
      "login",
      "sign in"
    ]
  },
  {
    "title": "Managing your subscription",
    "description": "Your Subscription settings show your current plan and give you a self-service billing portal for everything money-related.",
    "url": "/docs/account-and-settings/managing-your-subscription/",
    "keywords": [
      "managing",
      "subscription",
      "account",
      "settings",
      "billing",
      "invoice",
      "payment",
      "plan",
      "cancel",
      "upgrade"
    ]
  },
  {
    "title": "Setting up your email sending subdomain",
    "description": "To enable email sending from Storyraise, we'll walk through a quick 4-step process with you.",
    "url": "/docs/account-and-settings/email-subdomain-setup/",
    "keywords": [
      "setting",
      "email",
      "sending",
      "subdomain",
      "account",
      "settings",
      "setup",
      "dns",
      "spf",
      "dkim",
      "domain",
      "records",
      "cloudflare",
      "godaddy"
    ]
  },
  {
    "title": "Setting up a custom sending domain",
    "description": "When you send email through Storyraise, verifying your own sending domain makes your messages come clearly from your organization — and helps them reach the…",
    "url": "/docs/account-and-settings/custom-sending-domain/",
    "keywords": [
      "setting",
      "custom",
      "sending",
      "domain",
      "account",
      "settings",
      "dns",
      "spf",
      "dkim",
      "cname",
      "deliverability",
      "godaddy",
      "cloudflare",
      "from address"
    ]
  },
  {
    "title": "What is Storyraise Video?",
    "description": "Storyraise Video turns one recording into hundreds of personal video messages. Record once, and every constituent receives a version addressed to them — their…",
    "url": "/docs/storyraise-video/what-is-storyraise-video/",
    "keywords": [
      "what",
      "storyraise",
      "video"
    ]
  },
  {
    "title": "Creating a video message",
    "description": "A Storyraise Video message is one short recording, automatically personalized into a unique video for every recipient. This page is the end-to-end overview;…",
    "url": "/docs/storyraise-video/creating-a-video-message/",
    "keywords": [
      "creating",
      "video",
      "message",
      "storyraise"
    ]
  },
  {
    "title": "Recording your video",
    "description": "The video is the human heart of your message. Storyraise makes recording it painless — and handles transcription and captions for you afterward.",
    "url": "/docs/storyraise-video/recording-your-video/",
    "keywords": [
      "recording",
      "video",
      "storyraise"
    ]
  },
  {
    "title": "Scenes and personalization",
    "description": "Scenes are the on-screen text that appears over your video as you speak — and they're where each recipient's message becomes personally theirs.",
    "url": "/docs/storyraise-video/scenes-and-personalization/",
    "keywords": [
      "scenes",
      "personalization",
      "storyraise",
      "video"
    ]
  },
  {
    "title": "Sending and recipients",
    "description": "Your video is recorded and your scenes are personalized — now choose who receives it and send.",
    "url": "/docs/storyraise-video/sending-and-recipients/",
    "keywords": [
      "sending",
      "recipients",
      "storyraise",
      "video"
    ]
  },
  {
    "title": "What is Storyraise Collect?",
    "description": "Storyraise Collect gathers the raw material your stories are made of. Build a form, share the link, and collect stories, thank-yous, photos, and data from…",
    "url": "/docs/storyraise-collect/what-is-storyraise-collect/",
    "keywords": [
      "what",
      "storyraise",
      "collect"
    ]
  },
  {
    "title": "Creating a collection",
    "description": "A collection is a form plus everything it gathers. This guide takes you from an empty Collections view to a form ready to share.",
    "url": "/docs/storyraise-collect/creating-a-collection/",
    "keywords": [
      "creating",
      "collection",
      "storyraise",
      "collect"
    ]
  },
  {
    "title": "Form field types",
    "description": "Storyraise Collect gives you a full toolkit of fields, so your form can ask for exactly what you need — a quick quote, a long story, a photo, a date, a choice…",
    "url": "/docs/storyraise-collect/form-field-types/",
    "keywords": [
      "form",
      "field",
      "types",
      "storyraise",
      "collect"
    ]
  },
  {
    "title": "Multi-step forms",
    "description": "A long form on one page feels like a chore. Splitting it into steps makes it feel quick — and lets you collect repeating, one-to-many data cleanly.",
    "url": "/docs/storyraise-collect/multi-step-forms/",
    "keywords": [
      "multi",
      "step",
      "forms",
      "storyraise",
      "collect"
    ]
  },
  {
    "title": "Sharing your form",
    "description": "Once your form is built, share its link and the responses start flowing in. This page covers getting the form to people and what they experience filling it out.",
    "url": "/docs/storyraise-collect/sharing-your-form/",
    "keywords": [
      "sharing",
      "form",
      "storyraise",
      "collect"
    ]
  },
  {
    "title": "Managing responses",
    "description": "Everything people submit lands in a spreadsheet-style table you can actually work in — search it, clean it up, connect responses to constituents, and export it.",
    "url": "/docs/storyraise-collect/managing-responses/",
    "keywords": [
      "managing",
      "responses",
      "storyraise",
      "collect"
    ]
  },
  {
    "title": "Best practices",
    "description": "Patterns that separate the reports people finish from the ones they skim. Distilled from what works across Storyraise customers — use them as defaults, break…",
    "url": "/docs/resources/best-practices/",
    "keywords": [
      "best",
      "practices",
      "resources"
    ]
  },
  {
    "title": "Network requirements and troubleshooting",
    "description": "Storyraise is a web application, and your published reports are web pages. Both rely on a handful of Google, Firebase, and Storyraise services loading in the…",
    "url": "/docs/resources/network-requirements/",
    "keywords": [
      "network",
      "requirements",
      "troubleshooting",
      "resources",
      "firewall",
      "allowlist",
      "whitelist",
      "it",
      "blocked",
      "not loading",
      "images missing",
      "fonts",
      "logged out",
      "proxy",
      "vpn",
      "school",
      "corporate"
    ]
  },
  {
    "title": "Frequently asked questions",
    "description": "Quick answers to the questions we hear most. Each links to a fuller guide.",
    "url": "/docs/resources/faq/",
    "keywords": [
      "frequently",
      "asked",
      "questions",
      "resources",
      "faq"
    ]
  }
];
